CREATE TABLE alarm_reminder_queue_outbox (
    outbox_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_id  BIGINT    NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    CONSTRAINT fk_alarm_reminder_queue_outbox_reminder
        FOREIGN KEY (reminder_id) REFERENCES reminders (reminder_id)
);

CREATE INDEX idx_alarm_reminder_queue_outbox_reminder_id
    ON alarm_reminder_queue_outbox (reminder_id);
