CREATE TABLE reminder_outbox (
    outbox_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_id  BIGINT    NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    CONSTRAINT fk_reminder_outbox_reminder
        FOREIGN KEY (reminder_id) REFERENCES reminders (reminder_id)
);

CREATE INDEX idx_reminder_outbox_reminder_id
    ON reminder_outbox (reminder_id);
