-- 초기 스키마: JPA 엔티티(2026-07-12 기준)와 1:1로 매핑되는 테이블을 생성한다.
-- 이미 데이터가 있는 기존 환경(prod RDS 등)에서는 spring.flyway.baseline-on-migrate 설정에 의해
-- 이 스크립트가 실행되지 않고 V1이 baseline으로 기록된다. 완전히 비어 있는 스키마에서는 그대로 실행되어
-- 전체 테이블이 생성된다.

-- 1. 사용자
CREATE TABLE users (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role   VARCHAR(20)  NOT NULL,
    guest_id    VARCHAR(255),
    nickname    VARCHAR(100),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    deleted_at  TIMESTAMP
);

ALTER TABLE users
    ADD CONSTRAINT uq_users_guest_id UNIQUE (guest_id);

-- 2. 약관 마스터
CREATE TABLE terms (
    term_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_type   VARCHAR(50)  NOT NULL,
    is_required BOOLEAN      NOT NULL,
    version     VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);

ALTER TABLE terms
    ADD CONSTRAINT uq_terms_type_version UNIQUE (term_type, version);

-- 2-1. 사용자 약관 동의 이력 (users x terms)
CREATE TABLE user_agreed_terms (
    user_agreed_term_id BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT    NOT NULL,
    term_id               BIGINT    NOT NULL,
    created_at             TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_agreed_terms_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_agreed_terms_term FOREIGN KEY (term_id) REFERENCES terms (term_id)
);

CREATE INDEX idx_user_agreed_terms_user_id ON user_agreed_terms (user_id);
CREATE INDEX idx_user_agreed_terms_term_id ON user_agreed_terms (term_id);

-- 3. 인증(소셜 로그인) 정보
CREATE TABLE auths (
    auth_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    provider    VARCHAR(50)  NOT NULL,
    social_id   VARCHAR(255) NOT NULL,
    email       VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    deleted_at  TIMESTAMP,
    CONSTRAINT fk_auths_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_auths_user_id ON auths (user_id);

CREATE UNIQUE INDEX uq_auths_provider_social_id_active
    ON auths (provider, social_id)
    WHERE deleted_at IS NULL;

-- 4. 사용자 설정
CREATE TABLE user_settings (
    user_setting_id                        BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                                 BIGINT  NOT NULL,
    is_all_notification_enabled             BOOLEAN NOT NULL DEFAULT true,
    is_event_reminder_enabled               BOOLEAN NOT NULL DEFAULT true,
    is_action_item_reminder_enabled         BOOLEAN NOT NULL DEFAULT true,
    default_all_day_event_time              TIME    NOT NULL DEFAULT '09:00:00',
    default_action_item_time                TIME    NOT NULL DEFAULT '09:00:00',
    default_event_reminder_offset_minutes   INT     NOT NULL DEFAULT 30,
    is_feedback_data_collected              BOOLEAN NOT NULL DEFAULT false,
    is_personalization_enabled              BOOLEAN NOT NULL DEFAULT true,
    created_at                              TIMESTAMP NOT NULL,
    updated_at                              TIMESTAMP NOT NULL,
    deleted_at                              TIMESTAMP,
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

ALTER TABLE user_settings
    ADD CONSTRAINT uq_user_settings_user_id UNIQUE (user_id);

-- 5. 외부 캘린더 연동 계정
CREATE TABLE external_calendar_connections (
    external_calendar_connection_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                          BIGINT      NOT NULL,
    provider                         VARCHAR(50) NOT NULL,
    refresh_token                    VARCHAR(512),
    connection_status                VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at                       TIMESTAMP   NOT NULL,
    updated_at                       TIMESTAMP   NOT NULL,
    CONSTRAINT fk_external_calendar_connections_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_external_calendar_connections_user_id ON external_calendar_connections (user_id);

-- 6. 개별 외부 캘린더 목록
CREATE TABLE external_calendars (
    external_calendar_id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_calendar_connection_id BIGINT       NOT NULL,
    provider_external_calendar_id   VARCHAR(255) NOT NULL,
    name                             VARCHAR(255) NOT NULL,
    is_selected                     BOOLEAN      NOT NULL DEFAULT true,
    created_at                      TIMESTAMP    NOT NULL,
    updated_at                      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_external_calendars_connection
        FOREIGN KEY (external_calendar_connection_id)
        REFERENCES external_calendar_connections (external_calendar_connection_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_external_calendars_connection_id ON external_calendars (external_calendar_connection_id);

ALTER TABLE external_calendars
    ADD CONSTRAINT uq_external_calendars_connection_calendar
    UNIQUE (external_calendar_connection_id, provider_external_calendar_id);

-- 7. 일정
CREATE TABLE events (
    event_id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_calendar_id      BIGINT,
    source_text                TEXT,
    title                      VARCHAR(255) NOT NULL,
    description                TEXT,
    start_date                 DATE,
    start_datetime             TIMESTAMP,
    end_date                   DATE,
    end_datetime               TIMESTAMP,
    is_all_day                 BOOLEAN      NOT NULL DEFAULT false,
    is_recurring                BOOLEAN      NOT NULL DEFAULT false,
    recurrence_type             VARCHAR(50)  NOT NULL DEFAULT 'NONE',
    recurrence_interval         INT,
    recurrence_day_of_week      VARCHAR(50)  NOT NULL DEFAULT 'NONE',
    recurrence_day_of_month     INT,
    recurrence_end_date         TIMESTAMP,
    location                    VARCHAR(255),
    event_type_candidate        VARCHAR(50),
    event_type                  VARCHAR(50),
    source_type                 VARCHAR(50)  NOT NULL,
    event_status                VARCHAR(50)  NOT NULL DEFAULT 'CONFIRMED',
    external_event_id           VARCHAR(255),
    provider                    VARCHAR(50),
    created_at                  TIMESTAMP    NOT NULL,
    updated_at                  TIMESTAMP    NOT NULL,
    deleted_at                  TIMESTAMP,
    CONSTRAINT fk_events_external_calendar
        FOREIGN KEY (external_calendar_id)
        REFERENCES external_calendars (external_calendar_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_events_external_required
        CHECK (
            source_type <> 'EXTERNAL_CALENDAR'
            OR (external_calendar_id IS NOT NULL AND external_event_id IS NOT NULL)
        )
);

CREATE INDEX idx_events_external_calendar_id ON events (external_calendar_id);
CREATE INDEX idx_events_start_date_time ON events (start_date, start_datetime);

CREATE UNIQUE INDEX uq_events_external_calendar_event_active
    ON events (external_calendar_id, external_event_id)
    WHERE source_type = 'EXTERNAL_CALENDAR' AND deleted_at IS NULL;

-- 7-1. 사용자-일정 매핑 (일정 공유 확장성을 위한 N:M 브릿지)
CREATE TABLE user_events (
    user_event_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL,
    event_id        BIGINT      NOT NULL,
    event_role      VARCHAR(50) NOT NULL DEFAULT 'OWNER',
    created_at      TIMESTAMP   NOT NULL,
    CONSTRAINT fk_user_events_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_events_event FOREIGN KEY (event_id) REFERENCES events (event_id)
);

CREATE INDEX idx_user_events_user_id ON user_events (user_id);
CREATE INDEX idx_user_events_event_id ON user_events (event_id);

ALTER TABLE user_events
    ADD CONSTRAINT uq_user_events_user_id_event_id UNIQUE (user_id, event_id);

CREATE UNIQUE INDEX uq_user_events_owner
    ON user_events (event_id)
    WHERE event_role = 'OWNER';

-- 8. 준비/실행 항목
CREATE TABLE action_items (
    action_item_id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_event_id     BIGINT       NOT NULL,
    title                VARCHAR(255) NOT NULL,
    item_type            VARCHAR(50)  NOT NULL,
    display_date         DATE,
    display_datetime     TIMESTAMP,
    offset_days          INT,
    action_item_status   VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    created_by           VARCHAR(50)  NOT NULL,
    source_template_id   VARCHAR(100),
    created_at           TIMESTAMP    NOT NULL,
    updated_at           TIMESTAMP    NOT NULL,
    completed_at         TIMESTAMP,
    deleted_at           TIMESTAMP,
    CONSTRAINT fk_action_items_parent_event FOREIGN KEY (parent_event_id) REFERENCES events (event_id),
    CONSTRAINT ck_action_items_item_type
        CHECK (
            (item_type = 'TIMED_ACTION' AND display_date IS NOT NULL)
            OR (item_type = 'UNTIMED_PREP' AND display_date IS NULL AND display_datetime IS NULL)
            OR (item_type = 'UNRESOLVED')
        )
);

CREATE INDEX idx_action_items_parent_event_id ON action_items (parent_event_id);
CREATE INDEX idx_action_items_display_date_time ON action_items (display_date, display_datetime);

-- 9. 리마인드(푸시 알림 발송 큐)
CREATE TABLE reminders (
    reminder_id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT       NOT NULL,
    target_event_id         BIGINT,
    target_action_item_id   BIGINT,
    target_type             VARCHAR(50)  NOT NULL,
    scheduled_at             TIMESTAMP    NOT NULL,
    delivery_channel         VARCHAR(50)  NOT NULL DEFAULT 'PUSH',
    reminder_status          VARCHAR(50)  NOT NULL DEFAULT 'SCHEDULED',
    alarm_title              VARCHAR(100) NOT NULL,
    alarm_body               VARCHAR(255) NOT NULL,
    created_at               TIMESTAMP    NOT NULL,
    updated_at               TIMESTAMP    NOT NULL,
    CONSTRAINT fk_reminders_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_reminders_target_event
        FOREIGN KEY (target_event_id) REFERENCES events (event_id) ON DELETE CASCADE,
    CONSTRAINT fk_reminders_target_action_item
        FOREIGN KEY (target_action_item_id) REFERENCES action_items (action_item_id) ON DELETE CASCADE,
    CONSTRAINT ck_reminders_target_type
        CHECK (
            (target_type = 'EVENT' AND target_event_id IS NOT NULL AND target_action_item_id IS NULL)
            OR (target_type = 'TIMED_ACTION' AND target_event_id IS NULL AND target_action_item_id IS NOT NULL)
        )
);

CREATE INDEX idx_reminders_target_event_id ON reminders (target_event_id);
CREATE INDEX idx_reminders_target_action_item_id ON reminders (target_action_item_id);
CREATE INDEX idx_reminders_status_scheduled ON reminders (reminder_status, scheduled_at);

CREATE UNIQUE INDEX uq_reminders_event_schedule
    ON reminders (target_event_id, scheduled_at, delivery_channel)
    WHERE target_type = 'EVENT' AND target_event_id IS NOT NULL AND reminder_status = 'SCHEDULED';

CREATE UNIQUE INDEX uq_reminders_action_item_schedule
    ON reminders (target_action_item_id, scheduled_at, delivery_channel)
    WHERE target_type = 'TIMED_ACTION' AND target_action_item_id IS NOT NULL AND reminder_status = 'SCHEDULED';

-- 9-1. 추천 피드백 로그
CREATE TABLE recommendation_feedbacks (
    recommendation_feedback_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT      NOT NULL,
    event_id                    BIGINT,
    source_template_id          VARCHAR(100),
    action_type                  VARCHAR(50) NOT NULL,
    original_title                VARCHAR(255),
    edited_title                  VARCHAR(255),
    reason                        VARCHAR(255),
    created_at                    TIMESTAMP   NOT NULL,
    CONSTRAINT fk_recommendation_feedbacks_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_recommendation_feedbacks_event FOREIGN KEY (event_id) REFERENCES events (event_id)
);

CREATE INDEX idx_recommendation_feedbacks_user_id ON recommendation_feedbacks (user_id);
CREATE INDEX idx_recommendation_feedbacks_event_id ON recommendation_feedbacks (event_id);

-- 10. 일정 분석(맥락 구조화) 로그
CREATE TABLE event_analysis_logs (
    event_analysis_log_id    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                  BIGINT      NOT NULL,
    context_candidates        VARCHAR[],
    place_type_candidate       VARCHAR(50),
    condition_candidates       VARCHAR(255),
    temporal_profile           VARCHAR(50),
    preparation_need_level     VARCHAR(20),
    confidence_level           VARCHAR(20),
    created_at                 TIMESTAMP   NOT NULL,
    CONSTRAINT fk_event_analysis_logs_event FOREIGN KEY (event_id) REFERENCES events (event_id)
);

CREATE INDEX idx_event_analysis_logs_event_id ON event_analysis_logs (event_id);
